feature/omniauth
AC-005-Team/SoundClown pull request #6
Opened 2020-08-24 11:13 UTC by TeKaiPeng

Hello 可以登入囉😱 大大們幫我看一下唷

2020-08-24 13:07 UTC, tungchinlee approved these changes

2020-08-25 04:30 UTC, chaowudev commented on app/models/user.rb
> +    user = User.where(:google_token => access_token.credentials.token, :google_uid => access_token.uid ).first
```ruby
user = User.find_by(
              google_token: access_token.credentials.token,
              google_uid: access_token.uid
            )
```

2020-08-25 04:33 UTC, chaowudev commented on app/models/user.rb
> +      return user
改寫成這樣，外層的 if.. else.. 可以拿掉
```ruby
return user if user.present?
```

2020-08-27 09:51 UTC, Naoyakaoru approved these changes
gooooood

2020-08-28 04:24 UTC, boypie510 approved these changes

2020-08-28 14:05 UTC, boypie510 requested changes
下載到本機端，無法登入

2020-09-01 11:08 UTC, boypie510 approved these changes

2020-09-01 11:09 UTC, leegocode approved these changes

2020-09-01 11:11 UTC, merged